# Generated by Django 3.2 on 2020-09-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_star', '0002_movie_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.TextField(blank=True, null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.TextField(blank=True, null=True, verbose_name='genre'),
        ),
    ]
