# Generated by Django 3.2 on 2020-09-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_star', '0003_auto_20200924_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='amount_reviews',
            field=models.TextField(blank=True, null=True, verbose_name='genre'),
        ),
    ]
