# Generated by Django 3.2 on 2020-09-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_star', '0004_alter_movie_amount_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='amount_reviews',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='critics_consensus',
            field=models.TextField(blank=True, null=True, verbose_name='Consensus'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='genre'),
        ),
    ]
