# Generated by Django 3.2 on 2020-09-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_star', '0005_auto_20200925_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='PttMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Date')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Author')),
                ('contenttext', models.TextField(blank=True, null=True, verbose_name='Contenttext')),
            ],
        ),
    ]
